# CMake generated Testfile for 
# Source directory: /Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/InteriorPoint
# Build directory: /Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/InteriorPoint
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(AreaConstraint2D.CheckFunctions "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/InteriorPoint-test" "--gtest_filter=AreaConstraint2D.CheckFunctions" "--gtest_color=yes")
set_tests_properties(AreaConstraint2D.CheckFunctions PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:69" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/InteriorPoint/CMakeLists.txt;29;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/InteriorPoint/CMakeLists.txt;0;")
add_test(InteriorPointProblem.CheckFunctions "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/InteriorPoint-test" "--gtest_filter=InteriorPointProblem.CheckFunctions" "--gtest_color=yes")
set_tests_properties(InteriorPointProblem.CheckFunctions PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:110" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/InteriorPoint/CMakeLists.txt;29;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/InteriorPoint/CMakeLists.txt;0;")
add_test(InteriorPointMethod.CheckMinimum "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/InteriorPoint-test" "--gtest_filter=InteriorPointMethod.CheckMinimum" "--gtest_color=yes")
set_tests_properties(InteriorPointMethod.CheckMinimum PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:174" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/InteriorPoint/CMakeLists.txt;29;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/InteriorPoint/CMakeLists.txt;0;")
