# CMake generated Testfile for 
# Source directory: /Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial
# Build directory: /Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(EigenTutorial.MatrixInitialization_4x4_integers "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/EigenTutorial-test" "--gtest_filter=EigenTutorial.MatrixInitialization_4x4_integers" "--gtest_color=yes")
set_tests_properties(EigenTutorial.MatrixInitialization_4x4_integers PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:40" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;13;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;0;")
add_test(EigenTutorial.VectorInitialization_column_3_doubles "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/EigenTutorial-test" "--gtest_filter=EigenTutorial.VectorInitialization_column_3_doubles" "--gtest_color=yes")
set_tests_properties(EigenTutorial.VectorInitialization_column_3_doubles PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:48" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;13;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;0;")
add_test(EigenTutorial.VectorInitialization_row_5_floats "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/EigenTutorial-test" "--gtest_filter=EigenTutorial.VectorInitialization_row_5_floats" "--gtest_color=yes")
set_tests_properties(EigenTutorial.VectorInitialization_row_5_floats PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:55" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;13;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;0;")
add_test(EigenTutorial.MatrixInitialization_dynamic_3x3_doubles "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/EigenTutorial-test" "--gtest_filter=EigenTutorial.MatrixInitialization_dynamic_3x3_doubles" "--gtest_color=yes")
set_tests_properties(EigenTutorial.MatrixInitialization_dynamic_3x3_doubles PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:62" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;13;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;0;")
add_test(EigenTutorial.VectorInitialization_OnTheFly_column_float "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/EigenTutorial-test" "--gtest_filter=EigenTutorial.VectorInitialization_OnTheFly_column_float" "--gtest_color=yes")
set_tests_properties(EigenTutorial.VectorInitialization_OnTheFly_column_float PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:70" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;13;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;0;")
add_test(EigenTutorial.MatrixAssignment_dense "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/EigenTutorial-test" "--gtest_filter=EigenTutorial.MatrixAssignment_dense" "--gtest_color=yes")
set_tests_properties(EigenTutorial.MatrixAssignment_dense PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:82" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;13;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;0;")
add_test(EigenTutorial.MatrixAssignment_sparse "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/EigenTutorial-test" "--gtest_filter=EigenTutorial.MatrixAssignment_sparse" "--gtest_color=yes")
set_tests_properties(EigenTutorial.MatrixAssignment_sparse PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:116" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;13;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EigenTutorial/CMakeLists.txt;0;")
