# CMake generated Testfile for 
# Source directory: /Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation
# Build directory: /Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(MassSpringSystem.ProblemSetup "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/MassSpringProblemEvaluation-test" "--gtest_filter=MassSpringSystem.ProblemSetup" "--gtest_color=yes")
set_tests_properties(MassSpringSystem.ProblemSetup PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:37" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;26;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;0;")
add_test(SpringElements.SpringElement2DFunctions "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/MassSpringProblemEvaluation-test" "--gtest_filter=SpringElements.SpringElement2DFunctions" "--gtest_color=yes")
set_tests_properties(SpringElements.SpringElement2DFunctions PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:46" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;26;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;0;")
add_test(SpringElements.SpringElement2DWithLengthFunctions "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/MassSpringProblemEvaluation-test" "--gtest_filter=SpringElements.SpringElement2DWithLengthFunctions" "--gtest_color=yes")
set_tests_properties(SpringElements.SpringElement2DWithLengthFunctions PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:79" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;26;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;0;")
add_test(MassSpringProblem.MassSpringProblem2DDenseFunctions "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/MassSpringProblemEvaluation-test" "--gtest_filter=MassSpringProblem.MassSpringProblem2DDenseFunctions" "--gtest_color=yes")
set_tests_properties(MassSpringProblem.MassSpringProblem2DDenseFunctions PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:112" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;26;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;0;")
add_test(MassSpringProblem.MassSpringProblem2DSparseFunctions "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/MassSpringProblemEvaluation-test" "--gtest_filter=MassSpringProblem.MassSpringProblem2DSparseFunctions" "--gtest_color=yes")
set_tests_properties(MassSpringProblem.MassSpringProblem2DSparseFunctions PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:158" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;26;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;0;")
add_test(MassSpringProblem.MassSpringProblem2DSparseCheckDerivative "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/MassSpringProblemEvaluation-test" "--gtest_filter=MassSpringProblem.MassSpringProblem2DSparseCheckDerivative" "--gtest_color=yes")
set_tests_properties(MassSpringProblem.MassSpringProblem2DSparseCheckDerivative PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:207" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;26;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;0;")
add_test(MassSpringSystem.EnergyComputation "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/MassSpringProblemEvaluation-test" "--gtest_filter=MassSpringSystem.EnergyComputation" "--gtest_color=yes")
set_tests_properties(MassSpringSystem.EnergyComputation PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:222" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;26;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;0;")
add_test(MassSpringSystem.DenseVersusSparseSpeedComparison "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/MassSpringProblemEvaluation-test" "--gtest_filter=MassSpringSystem.DenseVersusSparseSpeedComparison" "--gtest_color=yes")
set_tests_properties(MassSpringSystem.DenseVersusSparseSpeedComparison PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:247" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;26;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/MassSpringProblemEvaluation/CMakeLists.txt;0;")
