# CMake generated Testfile for 
# Source directory: /Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests
# Build directory: /Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ConvexityTest.Quadratic2DisConvex "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.Quadratic2DisConvex" "--gtest_color=yes")
set_tests_properties(ConvexityTest.Quadratic2DisConvex PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:37" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;0;")
add_test(ConvexityTest.QuadraticNDisConvex "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.QuadraticNDisConvex" "--gtest_color=yes")
set_tests_properties(ConvexityTest.QuadraticNDisConvex PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:45" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;0;")
add_test(ConvexityTest.OtherQuadraticNDisConvex "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.OtherQuadraticNDisConvex" "--gtest_color=yes")
set_tests_properties(ConvexityTest.OtherQuadraticNDisConvex PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:56" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;0;")
add_test(ConvexityTest.YetAnotherQuadraticNDisConvex "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.YetAnotherQuadraticNDisConvex" "--gtest_color=yes")
set_tests_properties(ConvexityTest.YetAnotherQuadraticNDisConvex PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:67" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;0;")
add_test(ConvexityTest.NonConvex2DIsConvexOnCertainInterval "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.NonConvex2DIsConvexOnCertainInterval" "--gtest_color=yes")
set_tests_properties(ConvexityTest.NonConvex2DIsConvexOnCertainInterval PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:78" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;0;")
add_test(ConvexityTest.NonConvex2DIsNonConvexOnOtherInterval "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.NonConvex2DIsNonConvexOnOtherInterval" "--gtest_color=yes")
set_tests_properties(ConvexityTest.NonConvex2DIsNonConvexOnOtherInterval PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:88" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;0;")
add_test(ConvexityTest.NonConvex2DIsNonConvexOnYetAnotherInterval "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/ConvexityTests-test" "--gtest_filter=ConvexityTest.NonConvex2DIsNonConvexOnYetAnotherInterval" "--gtest_color=yes")
set_tests_properties(ConvexityTest.NonConvex2DIsNonConvexOnYetAnotherInterval PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:98" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;25;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/ConvexityTests/CMakeLists.txt;0;")
