# CMake generated Testfile for 
# Source directory: /Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EqualityConstrainedNewton
# Build directory: /Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EqualityConstrainedNewton
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(MassSpringSystemWithEqualityConstraints.ProjectOnAffine "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/EqualityConstrainedNewton-test" "--gtest_filter=MassSpringSystemWithEqualityConstraints.ProjectOnAffine" "--gtest_color=yes")
set_tests_properties(MassSpringSystemWithEqualityConstraints.ProjectOnAffine PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:52" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EqualityConstrainedNewton/CMakeLists.txt;29;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EqualityConstrainedNewton/CMakeLists.txt;0;")
add_test(MassSpringSystemWithEqualityConstraints.CheckMinimum "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/EqualityConstrainedNewton-test" "--gtest_filter=MassSpringSystemWithEqualityConstraints.CheckMinimum" "--gtest_color=yes")
set_tests_properties(MassSpringSystemWithEqualityConstraints.CheckMinimum PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:80" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EqualityConstrainedNewton/CMakeLists.txt;29;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/EqualityConstrainedNewton/CMakeLists.txt;0;")
