# CMake generated Testfile for 
# Source directory: /Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton
# Build directory: /Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(SpringElement2DWithoutLengthLeastSquare.FunctionsEvaluation "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/GaussNewton-test" "--gtest_filter=SpringElement2DWithoutLengthLeastSquare.FunctionsEvaluation" "--gtest_color=yes")
set_tests_properties(SpringElement2DWithoutLengthLeastSquare.FunctionsEvaluation PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:51" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;29;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;0;")
add_test(ConstrainedSpringElement2DLeastSquare.FunctionsEvaluation "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/GaussNewton-test" "--gtest_filter=ConstrainedSpringElement2DLeastSquare.FunctionsEvaluation" "--gtest_color=yes")
set_tests_properties(ConstrainedSpringElement2DLeastSquare.FunctionsEvaluation PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:79" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;29;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;0;")
add_test(SpringElement2DWithLengthLeastSquare.FunctionsEvaluation "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/GaussNewton-test" "--gtest_filter=SpringElement2DWithLengthLeastSquare.FunctionsEvaluation" "--gtest_color=yes")
set_tests_properties(SpringElement2DWithLengthLeastSquare.FunctionsEvaluation PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:104" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;29;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;0;")
add_test(SpringElement2DWithLengthLeastSquare.EnergyOfSpringAtRestIsAlwaysZero "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/GaussNewton-test" "--gtest_filter=SpringElement2DWithLengthLeastSquare.EnergyOfSpringAtRestIsAlwaysZero" "--gtest_color=yes")
set_tests_properties(SpringElement2DWithLengthLeastSquare.EnergyOfSpringAtRestIsAlwaysZero PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:134" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;29;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;0;")
add_test(MassSpringProblemWithoutLengthLeastSquares.InitialEnergy "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/GaussNewton-test" "--gtest_filter=MassSpringProblemWithoutLengthLeastSquares.InitialEnergy" "--gtest_color=yes")
set_tests_properties(MassSpringProblemWithoutLengthLeastSquares.InitialEnergy PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:171" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;29;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;0;")
add_test(MassSpringProblemWithLengthLeastSquares.InitialEnergy "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/GaussNewton-test" "--gtest_filter=MassSpringProblemWithLengthLeastSquares.InitialEnergy" "--gtest_color=yes")
set_tests_properties(MassSpringProblemWithLengthLeastSquares.InitialEnergy PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:201" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;29;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;0;")
add_test(MassSpringProblemWithLengthLeastSquares.convergesToSolution "/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/Build/bin/GaussNewton-test" "--gtest_filter=MassSpringProblemWithLengthLeastSquares.convergesToSolution" "--gtest_color=yes")
set_tests_properties(MassSpringProblemWithLengthLeastSquares.convergesToSolution PROPERTIES  DEF_SOURCE_LINE "unit_tests.cc:228" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/GoogleTest.cmake;438;add_test;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;29;gtest_add_tests;/Users/xiazixuan/Desktop/CS_Self_Learning/Course_in_Bern/Applied_Optimizaton/Exercise11/aopt-exercise11/GaussNewton/CMakeLists.txt;0;")
